# Generated by Django 4.2.3 on 2023-08-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ddesc',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='desc',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
